version: '3.9'

services:
  vaultwarden-app:
    container_name: vaultwarden-app
    image: vaultwarden/server:latest
    depends_on:
      - db
    env_file: .env
    volumes:
      - /volume1/docker/vaultwarden/data:/data
    restart: always
    ports:
      - 4001:80
  vaultwarden-db:
    container_name: vaultwarden-db
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${VW_DB_DATABASE}
      - MYSQL_USER=${VW_DB_USERNAME}
      - MYSQL_PASSWORD=${VW_DB_PASSWORD}
    volumes:
      - /volume1/docker/vaultwarden/mysql:/var/lib/mysql
    restart: always
