version: '3.9'

services:
  vaultwarden-app:
    container_name: vaultwarden-app
    image: vaultwarden/server:latest
    depends_on:
      - vaultwarden-db
    env_file: .env
    volumes:
      - /volume1/docker/vaultwarden/data:/data
    restart: always
    ports:
      - 4001:80
  vaultwarden-db:
    container_name: vaultwarden-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=${VW_DB_DATABASE}
      - POSTGRES_USER=${VW_DB_USERNAME}
      - POSTGRES_PASSWORD=${VW_DB_PASSWORD}
    volumes:
      - /volume1/docker/vaultwarden/postgres/data:/var/lib/postgresql/data
    restart: always
