version: "3.9"

services:
  app:
    container_name:  monica-app
    image: slifty/monica:latest
    depends_on:
      - db
    env_file: .env
    restart: always
    volumes:
      - /volume1/docker/monica/storage:/var/www/html/storage

  db:
    container_name:  monica-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - /volume1/docker/monica/postgresql:/var/lib/postgresql/data
    restart: always

  web:
    container_name:  monica-web
    build: ./web
    ports:
      - 4000:80
    restart: always
    volumes:
      - /volume1/docker/monica/storage:/var/www/html/storage:ro
    depends_on:
      - app
