# Run Monica with nginx proxy
#
# You might want to set these variables in you .env file:
#
#- APP_ENV=production
#- APP_URL with your domain (https scheme)
#- APP_KEY with a random string
#
#- DB_HOST=db
# See `db` container for these values:
#- DB_DATABASE=monica
#- DB_USERNAME=monica
#- DB_PASSWORD=secret
#

version: "3.9"

services:
  app:
    container_name:  monica-app
    image: monica:fpm
    depends_on:
      - db
    env_file: .env
    volumes:
      - /volume1/docker/monica/storage:/var/www/html/storage
    restart: always

  db:
    container_name:  monica-db
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /volume1/docker/monica/mysql:/var/lib/mysql
    restart: always

  web:
    container_name:  monica-web
    build: ./web
    ports:
      - 4000:80
    restart: always
    volumes:
      - /volume1/docker/monica/storage:/var/www/html/storage:ro
    depends_on:
      - app
